cask_args appdir: '/Applications'

tap 'caskroom/versions'
tap 'pivotal/tap'

# Java development
cask 'java'
cask 'intellij-idea'

brew 'groovy', args: ['with-invokedynamic']
brew 'gradle'

brew 'maven'
brew 'maven-completion'

brew 'springboot'

brew 'jmeter', args: ['with-plugins']
