cask_args appdir: '/Applications'

brew 'vim', args: ['--override-system-vi', '--with-python3', '--with-mzscheme', '--with-lua', '--with-luajit', '--with-tcl']

cask 'atom'

cask 'visual-studio-code'
