cask_args appdir: '/Applications'

cask 'torbrowser'
cask 'onionshare'
cask 'gpgtools'
cask 'lastpass'

brew 'tor', args: [ '--with-libnatpmp', '--with-libscrypt', '--with-miniupnpc' ]
brew 'arm'
brew 'gpg2', args: [ '--with-readline' ]

tap 'homebrew/fuse'
brew 'encfs'