cask_args appdir: '/Applications'

brew 'tor', args: [ '--with-libnatpmp', '--with-libscrypt', '--with-miniupnpc' ]
brew 'arm'
cask 'torbrowser'
cask 'onionshare'

brew 'gpg2', args: [ '--with-readline' ]
cask 'gpgtools'

cask 'lastpass'

tap 'homebrew/fuse'
brew 'encfs'