cask_args appdir: '/Applications'

brew 'open-completion'

# Convenience
cask 'cheatsheet'

# Browsers
cask 'google-chrome'

# Writing
cask 'scrivener'
cask 'grammarly'
cask 'markdown-service-tools'

# Idea theorem
cask 'anki'
cask 'evernote'
cask 'skitch'

# Reading
cask 'skim'

# Cloud drives
cask 'dropbox'
cask 'google-drive-file-stream'

# Multimedia
cask 'vlc'
cask 'transmission'

# Chat
cask 'slack'
cask 'telegram'
cask 'limechat'
cask 'skype'
