cask_args appdir: '/Applications'

brew 'open-completion'

# Usability
cask 'cheatsheet'

# Browsers
cask 'firefoxdeveloperedition'
cask 'google-chrome'

# Writing
cask 'scrivener'
cask 'grammarly'
cask 'evernote'
cask 'markdown-service-tools'

# Reading
cask 'skim'

# Backups
cask 'dropbox'
cask 'google-drive'

# Multimedia
cask 'vlc'
cask 'anki'
cask 'skitch'

# Chat
cask 'slack'
cask 'telegram'
cask 'limechat'

# Utilities
cask 'vmware-fusion'
cask 'cleanmymac'
cask 'transmission'

# Hardwares
cask 'logitech-options'