cask_args appdir: '/Applications'

# Install Quicklook plugins
# ref: https://github.com/sindresorhus/quick-look-plugins
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'qlprettypatch'
cask 'quicklook-csv'
cask 'betterzipql'
cask 'qlimagesize'
cask 'webpquicklook'
cask 'suspicious-package'
cask 'provisionql'

# Install QuickLook render plugin for ReST (ReStructuredText) files.
# ref: https://github.com/cluther/qlrest
cask 'qlrest'