cask_args appdir: '/Applications'

# Browsers
cask 'firefox'

# Writing
cask 'scrivener'

# Idea theorem
cask 'anki'
cask 'evernote'

# Cloud drives
cask 'google-drive'

# Multimedia
cask 'transmission'

# Chat
cask 'telegram'
cask 'discord'
