cask_args appdir: '/Applications'

# Compression
brew 'p7zip'

# Recovery
brew 'testdisk'

# Markdown
brew 'commonmark'

# File systems
cask 'osxfuse'

# File transfer
cask 'cyberduck'
brew 'duck'
## aria2 is a lightweight multi-protocol & multi-source command-line download utility
brew 'aria2', args: ['-—with-libssh2']