cask_args appdir: '/Applications'

brew 'git', args: ['--with-blk-sha1', '--with-brewed-curl', '--with-brewed-openssl', '--with-brewed-svn', '--with-gettext', '--with-pcre' '--with-persistent-https']

brew 'git-lfs'
